"""Add date and storage fields to tickets

Revision ID: 6fe403fe4c32
Revises: b5e75b965af1
Create Date: 2025-10-16 13:13:09.383038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe403fe4c32'
down_revision: Union[str, None] = 'b5e75b965af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###