"""Add date and storage fields to tickets

Revision ID: 8d85c509f29d
Revises: 4d5b6c7e8f90
Create Date: 2025-10-15 13:50:15.823568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d85c509f29d'
down_revision: Union[str, None] = '4d5b6c7e8f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('departure_date', sa.Date(), nullable=True))
    op.add_column('tickets', sa.Column('arrival_date', sa.Date(), nullable=True))
    op.add_column('tickets', sa.Column('storage_key', sa.String(), nullable=True))
    op.drop_column('tickets', 'event_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'storage_key')
    op.drop_column('tickets', 'arrival_date')
    op.drop_column('tickets', 'departure_date')
    # ### end Alembic commands ###