"""Add date and storage fields to tickets

Revision ID: b5e75b965af1
Revises: 8d85c509f29d
Create Date: 2025-10-16 00:33:50.900872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e75b965af1'
down_revision: Union[str, None] = '8d85c509f29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('passenger_name', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('train_number', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('wagon_number', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('seat_number', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('departure_station', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('departure_datetime', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('arrival_station', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('arrival_datetime', sa.DateTime(), nullable=True))
    op.drop_column('tickets', 'arrival_date')
    op.drop_column('tickets', 'departure_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('departure_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('arrival_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'arrival_datetime')
    op.drop_column('tickets', 'arrival_station')
    op.drop_column('tickets', 'departure_datetime')
    op.drop_column('tickets', 'departure_station')
    op.drop_column('tickets', 'seat_number')
    op.drop_column('tickets', 'wagon_number')
    op.drop_column('tickets', 'train_number')
    op.drop_column('tickets', 'passenger_name')
    # ### end Alembic commands ###