"""initial migration

Revision ID: 5c1a8b3d7e9f
Revises:
Create Date: 2025-10-13 00:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1a8b3d7e9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_scheduled_notifications_send_at'), 'scheduled_notifications', ['send_at'], unique=False)
    op.create_index(op.f('ix_scheduled_notifications_status'), 'scheduled_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_notifications_user_id'), 'scheduled_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_notifications_user_id'), table_name='scheduled_notifications')
    op.drop_index(op.f('ix_scheduled_notifications_status'), table_name='scheduled_notifications')
    op.drop_index(op.f('ix_scheduled_notifications_send_at'), table_name='scheduled_notifications')
    op.drop_table('scheduled_notifications')
    # ### end Alembic commands ###